### ISSUE TITLE
How much RAM  is required for training?

### ISSUE THREAD

**Issue by zyweven** [flyinglynx/Bilinear-Matching-Network#2]
Now I have 24G RAM and 12G GPU memory. But when I train, I always get this in epoch 1

```shell 
RuntimeError: DataLoader worker (pid 15666) is killed by signal: Killed. 
```

This seems to be the reason for not having enough RAM . How much RAM  is required during training?
Thank you very much

**Comment by flyinglynx** [comment]
Hi! Actually, the requirement for RAM is relatively high (around 30G), because we preload the whole dataset into the memory in our code. But this is avoidable at the cost of some additional training time (reading data from disk). Please change default value for `preload` argument in line 64 of `FSC147_dataset.py` from `True` to `False`.  We will modify the code so that the preload choice for dataset can be modified in the configuration file.

**Comment by zyweven** [comment]
> Hi! Actually, the requirement for RAM is relatively high (around 30G), because we preload the whole dataset into the memory in our code. But this is avoidable at the cost of some additional training time (reading data from disk). Please change default value for `preload` argument in line 64 of `FSC147_dataset.py` from `True` to `False`. We will modify the code so that the preload choice for dataset can be modified in the configuration file.

thanks for your answer！:)

**Comment by wjun0830** [comment]
May I ask for the required GPU memory (Approximately) for the experiments?

Thanks. Regards
