### ISSUE TITLE
image size and density map size

### ISSUE THREAD

**Issue by trungpham2606** [flyinglynx/Bilinear-Matching-Network#3]
Dear @flyinglynx 
In your dataloader code, I see that img will be resized (in a range), but I dont see where you change the density map's size as well ?
Do I miss anything here :-?

**Comment by flyinglynx** [comment]
Hi! Thank u, that's an error in our code. But it will not trigger any error during training. Because all the images in FSC-147 have already satisfied the size requirement. Maybe authors of FSC-147 have preprocessed the dataset. We will fix this issue, and you can implement a simple interpolation (opencv or torch have some functions to do so) to resize the density maps as well.

**Comment by trungpham2606** [comment]
@flyinglynx 
I see ^^. thank you
Btw, do you have the code to generate gt density map ?

**Comment by flyinglynx** [comment]
> 
Sorry, I used the provided density maps. I see some relevant issues in "https://github.com/cvlab-stonybrook/LearningToCountEverything". Maybe their discussion can help you.
